name: Docker Image CI

on:
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nouvelle0epoch/lne-channel
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v1
    - name: Update docker-compose
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.PROD_HOST }}
        USERNAME: ${{ secrets.PROD_USERNAME }}
        PORT: ${{ secrets.PROD_PORT }}
        KEY: ${{ secrets.PROD_KEY }}
      with:
        source: "docker-compose.yml"
        target: "/home/ubuntu/channels"
    - name: Pull docker image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USERNAME }}
        key: ${{ secrets.PROD_KEY }}
        port: ${{ secrets.PROD_PORT }}
        script: sudo docker pull nouvelle0epoch/lne-channel
    - name: Restart docker-compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USERNAME }}
        key: ${{ secrets.PROD_KEY }}
        port: ${{ secrets.PROD_PORT }}
        script: cd /home/ubuntu/channels && sudo docker-compose down && sudo docker-compose up -d